build: enable cmake in curl build
Tryed to chang autoconf tools in Curl build to cmake use for builds
where cmake major starts from 3. It was made so because cmake in curl
build works only with 3.0 version and above, the following issue
found on:
  CentOS 6,7
  Ubuntu 14.04

Issue with curl cmake based build with cmake before 3.0 version:
  CMake Error at CMakeLists.txt:41 (cmake_minimum_required):
    CMake 3.0 or higher is required.  You are running version 2.8.12.2

For curl cmake build all autoconf options were ported to cmake
configuration call.

Also found that CURL cmake configuration file:
  third_party/curl/lib/CMakeLists.txt

has installation part for built libcurl.a library:
  install(TARGETS ${LIB_NAME}
    EXPORT ${TARGETS_EXPORT_NAME}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}

where it changes CMAKE_INSTALL_LIBDIR to appropriate name with
suffix of the architecture, like:
  lib
  lib64
  x86_64

Found that find_library routine from the file:
  cmake/FindLibCURL.cmake
returns only 'lib' value and it breaks the building of the depends
binaries. To avoid of it the CMAKE_INSTALL_LIBDIR option was set to
cmake call:
  -DCMAKE_INSTALL_LIBDIR=lib

Completely changed autoconf to cmake in curl build. After curl
sources were changed to be able to be build since 2.8 version
the old OS like CentOS 6/7 and Ubuntu 14.04 became available
for curl build using cmake.

Autoconf part completely removed and code cleaned up for cmake.

1. Found issue with building on CentOS 6:

     Linking C executable curl
     build/ares/dest/lib/libcares.a(ares__timeval.c.o): In function `ares__tvnow':
     ares__timeval.c:(.text+0x15): undefined reference to `clock_gettime'
     collect2: error: ld returned 1 exit status

   It was fixed with added "-lrt" flag to CMAKE_C_FLAGS and
   CMAKE_CXX_FLAGS build flags, when cmake version is lower
   than 3.0 and RT library had needed function.

2. Found issue with building FreeBSD 12: app/socket test failed.

     [035] --- app/socket.result	Tue May 26 03:06:32 2020
     [035] +++ app/socket.reject	Fri May  8 08:26:16 2020
     [035] @@ -836,7 +836,7 @@
     [035]  ...
     [035]  s:recv()
     [035]  ---
     [035] -- Hello, world
     [035] +-
     [035]  ...
     [035]  sc:sendto('127.0.0.1', s:name().port, 'Hello, world, 2')
     [035]  ---

   It was fixed with added "-DLDFLAGS=" flag to cmake call.

3. Found issue with static build using CentOS 7, where SSL cmake rule
   failed.

   It was fixed in issue #5019.

Closes #4968
Closes #5020